### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by benmarwick** [Pakillo/template#2]
I really like this template and have learned a lot by studying its organisation. 

Do you have an example of this template being used for a real-world report or publication?

**Comment by Pakillo** [comment]
Hi @benmarwick 

Thanks for your interest. We are using the template for several ongoing projects. None is yet published, but I could share some with you so that you can have a look

**Comment by benmarwick** [comment]
Thanks very much, I will study those with interest. If any are published or otherwise publicly available, please let me know so I can cite them!
