### ISSUE TITLE
package versions

### ISSUE THREAD

**Issue by jasonserviss** [Pakillo/template#6]
Hello,

This is a really good idea (i.e. using R packages to facilitate reproducibility) and I have been doing this for sometime. I would like to suggest an additional step and that is being able to replicate R version and package versions since, obviously, changes in package code/functions overtime can break your analysis code. Ideally we would be able to set a R and package version in the DESCRIPTION file, and I can remember some rather recent discussion concerning this on the Bioconductor Developer mailing list, but, as far as I understood, this is not possible at the moment (probably stemming from the fact that, even though they are a practical solution, R packages were not thought to serve the purpose we want to use them for). I have recently resolved this using the liftr package and docker. I made a 'quick and dirty' example at [reproducibleAnalysis](https://github.com/jasonserviss/reproducibleAnalysis) for you to have a look at if you would like. I don't know if this is the best solution but it may be a starting point to work from. Id also be glad to hear any comments you might have!

Kind Regards,
Jason

**Comment by Pakillo** [comment]
Hi @jasonserviss 

Thank you for your comment, and sorry for the late reply. I hadn't looked at this package for some time. I've now slightly revised it, and finally preferred to leave it open to the user how they want to record and manage dependencies. I do suggest some alternatives, like using automagic, renv, or Docker, but people are free to use any approach they like.
Thanks again!
